INSERT INTO CATALOG_CATEGORY VALUES (1,'Oficios Generales','Oficios Generales',1);
INSERT INTO CATALOG_CATEGORY VALUES (2,'Cuidado Personal','Cuidado Personal',1);
INSERT INTO CATALOG_CATEGORY VALUES (3,'Automotriz','Automotriz',1);
INSERT INTO CATALOG_CATEGORY VALUES (4,'Cuidado de Mascota','Cuidado de Mascota',1);
INSERT INTO CATALOG_CATEGORY VALUES (5,'Limpieza','Limpieza',1);
INSERT INTO CATALOG_CATEGORY VALUES (6,'Deportes','Deportes',1);
INSERT INTO CATALOG_CATEGORY VALUES (7,'Eventos','Eventos',1);
INSERT INTO CATALOG_CATEGORY VALUES (8,'Otros','Otros',1);

INSERT INTO CATALOG_EMPLEO VALUES (1,'Carpinteros',1,'Carpinteros',1);
INSERT INTO CATALOG_EMPLEO VALUES (2,'Plomero',1,'Plomero',1);
INSERT INTO CATALOG_EMPLEO VALUES (3,'Electricista',1,'Electricista',1);
INSERT INTO CATALOG_EMPLEO VALUES (4,'Aire Acondicionado/Refrigedadores',1,'Aire Acondicionado/Refrigedadores',1);
INSERT INTO CATALOG_EMPLEO VALUES (5,'Calentador Solar',1,'Calentador Solar',1);
INSERT INTO CATALOG_EMPLEO VALUES (6,'Albanil',1,'Albanil',1);
INSERT INTO CATALOG_EMPLEO VALUES (7,'Pintor',1,'Pintor',1);
INSERT INTO CATALOG_EMPLEO VALUES (8,'Jardinero',1,'Jardinero',1);
INSERT INTO CATALOG_EMPLEO VALUES (9,'Estilista',2,'Estilista',1);
INSERT INTO CATALOG_EMPLEO VALUES (10,'Pedicurisca/Podologo',2,'Pedicurisca/Podologo',1);
INSERT INTO CATALOG_EMPLEO VALUES (11,'SPA',2,'SPA',1);
INSERT INTO CATALOG_EMPLEO VALUES (12,'Mecanico',3,'Mecanico',1);
INSERT INTO CATALOG_EMPLEO VALUES (13,'Mecanico Electrico',3,'Mecanico Electrico',1);
INSERT INTO CATALOG_EMPLEO VALUES (14,'Llantero',3,'Llantero',1);
INSERT INTO CATALOG_EMPLEO VALUES (15,'Limpieza de Automovil',3,'Limpieza de Automovil',1);
INSERT INTO CATALOG_EMPLEO VALUES (16,'Veterinario',4,'Veterinario',1);
INSERT INTO CATALOG_EMPLEO VALUES (17,'Estetica para mascota',4,'Estetica para mascota',1);
INSERT INTO CATALOG_EMPLEO VALUES (18,'Limpieza negocios',5,'Limpieza negocios',1);
INSERT INTO CATALOG_EMPLEO VALUES (19,'Ayuda Domestica',5,'Ayuda Domestica',1);
INSERT INTO CATALOG_EMPLEO VALUES (20,'Limpieza de Automovil',5,'Limpieza de Automovil',1);
INSERT INTO CATALOG_EMPLEO VALUES (21,'Instructor en alguna diciplina',6,'Instructor en alguna diciplina',1);
INSERT INTO CATALOG_EMPLEO VALUES (22,'Meseros',7,'Meseros',1);
INSERT INTO CATALOG_EMPLEO VALUES (23,'Cocinero',7,'Cocinero',1);
INSERT INTO CATALOG_EMPLEO VALUES (24,'Entretenimiento',7,'Entretenimiento',1);
INSERT INTO CATALOG_EMPLEO VALUES (25,'Sastreria',8,'Sastreria',1);
INSERT INTO CATALOG_EMPLEO VALUES (26,'Asitente Admistrativa',8,'Asitente Admistrativa',1);
INSERT INTO CATALOG_EMPLEO VALUES (27,'Apoyo a Eduacion en Casa',8,'Apoyo a Eduacion en Casa',1);
INSERT INTO CATALOG_EMPLEO VALUES (28,'Guaderia en Casa',8,'Guaderia en Casa',1);

INSERT INTO CATALOG_SKILL VALUES (1,'Muebles','Muebles',1,1);
INSERT INTO CATALOG_SKILL VALUES (2,'Closets','Closets',1,1);
INSERT INTO CATALOG_SKILL VALUES (3,'Cocina','Cocina',1,1);
INSERT INTO CATALOG_SKILL VALUES (4,'General','General',2,1);
INSERT INTO CATALOG_SKILL VALUES (5,'Lampara','Lampara',3,1);
INSERT INTO CATALOG_SKILL VALUES (6,'Television','Television',3,1);
INSERT INTO CATALOG_SKILL VALUES (7,'Red Electrica','Red Electrica',3,1);
INSERT INTO CATALOG_SKILL VALUES (8,'Electrodomesticos','Electrodomesticos',3,1);
INSERT INTO CATALOG_SKILL VALUES (9,'Otros/Varios','Otros/Varios',3,1);
INSERT INTO CATALOG_SKILL VALUES (10,'Construccion','Construccion',6,1);
INSERT INTO CATALOG_SKILL VALUES (11,'Mantenimiento','Mantenimiento',6,1);
INSERT INTO CATALOG_SKILL VALUES (12,'Remodelaciones','Remodelaciones',6,1);
INSERT INTO CATALOG_SKILL VALUES (13,'Exterior','Exterior',7,1);
INSERT INTO CATALOG_SKILL VALUES (14,'Interior','Interior',7,1);
INSERT INTO CATALOG_SKILL VALUES (15,'impermeabilizante','impermeabilizante',7,1);
INSERT INTO CATALOG_SKILL VALUES (16,'Cortar Cesped','Cortar Cesped',8,1);
INSERT INTO CATALOG_SKILL VALUES (17,'Plantas/Arboles','Plantas/Arboles',8,1);
INSERT INTO CATALOG_SKILL VALUES (18,'Corte Cabello','Corte Cabello',9,1);
INSERT INTO CATALOG_SKILL VALUES (19,'Gelish','Gelish',9,1);
INSERT INTO CATALOG_SKILL VALUES (20,'Tinte','Tinte',9,1);
INSERT INTO CATALOG_SKILL VALUES (21,'Otros','Otros',9,1);
INSERT INTO CATALOG_SKILL VALUES (22,'Uñas','Uñas',10,1);
INSERT INTO CATALOG_SKILL VALUES (23,'Pies','Pies',10,1);
INSERT INTO CATALOG_SKILL VALUES (24,'Otros/Varios','Otros/Varios',10,1);
INSERT INTO CATALOG_SKILL VALUES (25,'Masajes de Presion','Masajes de Presion',11,1);
INSERT INTO CATALOG_SKILL VALUES (26,'Cuidado Facial','Cuidado Facial',11,1);
INSERT INTO CATALOG_SKILL VALUES (27,'Otros/Varios','Otros/Varios',11,1);

INSERT INTO PROVIDER VALUES(1,12, 'Gegrorio','M','Gonzales');
INSERT INTO SKILL_PROVIDER values(1,1);
