INSERT INTO CATALOG_CATEGORY VALUES (1,'Oficios Generales','Oficios Generales',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Cuidado Personal','Cuidado Personal',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Automotriz','Automotriz',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Cuidado de Mascota','Cuidado de Mascota',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Limpieza','Limpieza',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Deportes','Deportes',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Eventos','Eventos',1);
INSERT INTO CATALOG_CATEGORY VALUES (1,'Otros','Otros',1);

INSERT INTO CATALOG_EMPLEO VALUES (1,'Carpinteros',1,'Carpinteros',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Plomero',1,'Plomero',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Electricista',1,'Electricista',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Aire Acondicionado/Refrigedadores',1,'Aire Acondicionado/Refrigedadores',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Calentador Solar',1,'Calentador Solar',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Albanil',1,'Albanil',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Pintor',1,'Pintor',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Jardinero',1,'Jardinero',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Estilista',2,'Estilista',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Pedicurisca/Podologo',2,'Pedicurisca/Podologo',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'SPA',2,'SPA',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Mecanico',3,'Mecanico',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Mecanico Electrico',3,'Mecanico Electrico',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Llantero',3,'Llantero',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Limpieza de Automovil',3,'Limpieza de Automovil',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Veterinario',4,'Veterinario',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Estetica para mascota',4,'Estetica para mascota',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Limpieza negocios',5,'Limpieza negocios',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Ayuda Domestica',5,'Ayuda Domestica',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Limpieza de Automovil',5,'Limpieza de Automovil',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Instructor en alguna diciplina',6,'Instructor en alguna diciplina',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Meseros',7,'Meseros',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Cocinero',7,'Cocinero',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Entretenimiento',7,'Entretenimiento',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Sastreria',8,'Sastreria',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Asitente Admistrativa',8,'Asitente Admistrativa',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Apoyo a Eduacion en Casa',8,'Apoyo a Eduacion en Casa',1);
INSERT INTO CATALOG_EMPLEO VALUES (1,'Guaderia en Casa',8,'Guaderia en Casa',1);

INSERT INTO CATALOG_SKILL VALUES (1,'Muebles','Muebles',1,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Closets','Closets',1,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Cocina','Cocina',1,1);
INSERT INTO CATALOG_SKILL VALUES (1,'General','General',2,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Lampara','Lampara',3,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Television','Television',3,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Red Electrica','Red Electrica',3,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Electrodomesticos','Electrodomesticos',3,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Otros/Varios','Otros/Varios',3,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Construccion','Construccion',6,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Mantenimiento','Mantenimiento',6,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Remodelaciones','Remodelaciones',6,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Exterior','Exterior',7,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Interior','Interior',7,1);
INSERT INTO CATALOG_SKILL VALUES (1,'impermeabilizante','impermeabilizante',7,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Cortar Cesped','Cortar Cesped',8,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Plantas/Arboles','Plantas/Arboles',8,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Corte Cabello','Corte Cabello',9,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Gelish','Gelish',9,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Tinte','Tinte',9,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Otros','Otros',9,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Uñas','Uñas',10,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Pies','Pies',10,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Otros/Varios','Otros/Varios',10,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Masajes de Presion','Masajes de Presion',11,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Cuidado Facial','Cuidado Facial',11,1);
INSERT INTO CATALOG_SKILL VALUES (1,'Otros/Varios','Otros/Varios',11,1);

INSERT INTO PROVIDER VALUES(1,12, 'Gegrorio','M','Gonzales');
INSERT INTO SKILL_PROVIDER values(1,1);
